<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
        <ContentTargetFolders>.</ContentTargetFolders>

        <RootNamespace>Umbraco.Community.BlockPreview</RootNamespace>
        <Product>Umbraco.Community.BlockPreview</Product>
        <PackageId>Umbraco.Community.BlockPreview</PackageId>
        <Title>BlockPreview</Title>
        <Description>Easy to use rich HTML backoffice previews for the Umbraco Block Grid, Block List and Rich Text editors</Description>
        <PackageTags>umbraco plugin package block list grid umbraco-marketplace</PackageTags>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

        <PackageIcon>icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Umbraco.Cms.Core" />
        <PackageReference Include="Umbraco.Cms.Web.Common" />
        <PackageReference Include="Umbraco.Cms.Web.Website" />
        <PackageReference Include="Umbraco.Cms.Api.Common" />
        <PackageReference Include="Umbraco.Cms.Api.Management" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="buildTransitive\**" PackagePath="buildTransitive" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\.github\assets\icon.png">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\..\.github\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Umbraco.Community.BlockPreview.UI\Umbraco.Community.BlockPreview.UI.esproj">
            <ReferenceOutputAssembly>False</ReferenceOutputAssembly>
        </ProjectReference>
    </ItemGroup>

    <!-- Add JSON schema file to package output -->
    <PropertyGroup>
        <_BlockPreviewJsonSchemaReference>appsettings-schema.BlockPreview.json</_BlockPreviewJsonSchemaReference>
    </PropertyGroup>

    <!-- Generate JSON schema on build (and before copying to project) -->
    <Target Name="GenerateAppsettingsSchema" BeforeTargets="Build;CopyUmbracoJsonSchemaFiles" Condition="!Exists('$(_BlockPreviewJsonSchemaReference)')">
        <Message Text="Generating $(_BlockPreviewJsonSchemaReference) because it doesn't exist" Importance="high" />
        <Exec WorkingDirectory="$(MSBuildThisFileDirectory)..\..\tools\Umbraco.Community.BlockPreview.SchemaGenerator" Command="dotnet run --configuration $(Configuration) -- --outputFile &quot;$(MSBuildThisFileDirectory)$(_BlockPreviewJsonSchemaReference)&quot;" />
    </Target>

    <!-- Remove generated JSON schema on clean -->
    <Target Name="RemoveAppsettingsSchema" AfterTargets="Clean" Condition="Exists('$(_BlockPreviewJsonSchemaReference)')">
        <Delete Files="$(_BlockPreviewJsonSchemaReference)" />
    </Target>

    <!-- Update umbraco-package.json files with current build version -->
    <!-- Assumes that the client assets have already been built to wwwroot -->
    <Target Name="UpdatePackageManifestVersion" BeforeTargets="Build" DependsOnTargets="GetBuildVersion;GetUmbracoBuildVersion" Condition="Exists('wwwroot\App_Plugins\Umbraco.Community.BlockPreview\umbraco-package.json')">
        <Message Text="Update umbraco-package.json files with current build version" Importance="high" />
        <ItemGroup>
            <_PackageManifestFiles Include="wwwroot\App_Plugins\Umbraco.Community.BlockPreview\umbraco-package.json" />
        </ItemGroup>
        <JsonPathUpdateValue JsonFile="%(_PackageManifestFiles.FullPath)" Path="$.version" Value="&quot;$(PackageVersion)&quot;" />
    </Target>
</Project>
