<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<StaticWebAssetBasePath>/</StaticWebAssetBasePath>
		<ContentTargetFolders>.</ContentTargetFolders>

		<RootNamespace>Umbraco.Community.BlockPreview</RootNamespace>
		<Product>Umbraco.Community.BlockPreview</Product>
		<PackageId>Umbraco.Community.BlockPreview</PackageId>
		<Title>Umbraco.Community.BlockPreview</Title>
		<Description>Easy to use rich HTML backoffice previews for the Umbraco Block List and Block Grid editors</Description>
		<PackageTags>umbraco plugin package block list grid umbraco-marketplace</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>

		<VersionPrefix>2.1.0</VersionPrefix>
		<VersionSuffix></VersionSuffix>
		<Authors>Rick Butterfield, Dave Woestenborghs, Matthew Wise</Authors>
		<Copyright>$([System.DateTime]::UtcNow.ToString(`yyyy`)) © Rick Butterfield</Copyright>

		<PackageProjectUrl>https://github.com/rickbutterfield/Umbraco.Community.BlockPreview</PackageProjectUrl>
		<RepositoryUrl>https://github.com/rickbutterfield/Umbraco.Community.BlockPreview</RepositoryUrl>
		<PackageIcon>icon.png</PackageIcon>

		<RepositoryType>git</RepositoryType>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Umbraco.Cms.Core" Version="[14.2.0, 15.0.0)" />
		<PackageReference Include="Umbraco.Cms.Web.Common" Version="[14.2.0, 15.0.0)" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="[14.2.0, 15.0.0)" />
		<PackageReference Include="Umbraco.Cms.Api.Common" Version="[14.2.0, 15.0.0)" />
		<PackageReference Include="Umbraco.Cms.Api.Management" Version="[14.2.0, 15.0.0)" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="buildTransitive\**" PackagePath="buildTransitive" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="NotificationHandlers\**" />
	  <Content Remove="NotificationHandlers\**" />
	  <EmbeddedResource Remove="NotificationHandlers\**" />
	  <None Remove="NotificationHandlers\**" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\.github\assets\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\.github\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="appsettings-schema.blockpreview.json" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Umbraco.Community.BlockPreview.UI\Umbraco.Community.BlockPreview.UI.esproj">
			<ReferenceOutputAssembly>False</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>
</Project>
