// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetGridStylesheetData, GetGridStylesheetErrors, GetGridStylesheetResponses, GetListStylesheetData, GetListStylesheetErrors, GetListStylesheetResponses, GetSettingsData, GetSettingsResponses, PreviewGridBlockData, PreviewGridBlockResponses, PreviewListBlockData, PreviewListBlockResponses, PreviewRichTextMarkupData, PreviewRichTextMarkupResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class BlockPreviewService {
    public static previewGridBlock<ThrowOnError extends boolean = true>(options?: Options<PreviewGridBlockData, ThrowOnError>) {
        return (options?.client ?? client).post<PreviewGridBlockResponses, unknown, ThrowOnError>({
            url: '/umbraco/block-preview/api/v1/preview/grid',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getGridStylesheet<ThrowOnError extends boolean = true>(options?: Options<GetGridStylesheetData, ThrowOnError>) {
        return (options?.client ?? client).get<GetGridStylesheetResponses, GetGridStylesheetErrors, ThrowOnError>({
            url: '/umbraco/block-preview/api/v1/preview/grid/stylesheet',
            ...options
        });
    }
    
    public static previewListBlock<ThrowOnError extends boolean = true>(options?: Options<PreviewListBlockData, ThrowOnError>) {
        return (options?.client ?? client).post<PreviewListBlockResponses, unknown, ThrowOnError>({
            url: '/umbraco/block-preview/api/v1/preview/list',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getListStylesheet<ThrowOnError extends boolean = true>(options?: Options<GetListStylesheetData, ThrowOnError>) {
        return (options?.client ?? client).get<GetListStylesheetResponses, GetListStylesheetErrors, ThrowOnError>({
            url: '/umbraco/block-preview/api/v1/preview/list/stylesheet',
            ...options
        });
    }
    
    public static previewRichTextMarkup<ThrowOnError extends boolean = true>(options?: Options<PreviewRichTextMarkupData, ThrowOnError>) {
        return (options?.client ?? client).post<PreviewRichTextMarkupResponses, unknown, ThrowOnError>({
            url: '/umbraco/block-preview/api/v1/preview/rte',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getSettings<ThrowOnError extends boolean = true>(options?: Options<GetSettingsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetSettingsResponses, unknown, ThrowOnError>({
            url: '/umbraco/block-preview/api/v1/settings',
            ...options
        });
    }
}
