// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { PreviewGridBlockData, PreviewGridBlockResponses, PreviewListBlockData, PreviewListBlockResponses, PreviewRichTextMarkupData, PreviewRichTextMarkupResponses, GetSettingsData, GetSettingsResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class BlockPreviewService {
    public static previewGridBlock<ThrowOnError extends boolean = true>(options?: Options<PreviewGridBlockData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PreviewGridBlockResponses, unknown, ThrowOnError>({
            url: '/umbraco/block-preview/api/v1/preview/grid',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static previewListBlock<ThrowOnError extends boolean = true>(options?: Options<PreviewListBlockData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PreviewListBlockResponses, unknown, ThrowOnError>({
            url: '/umbraco/block-preview/api/v1/preview/list',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static previewRichTextMarkup<ThrowOnError extends boolean = true>(options?: Options<PreviewRichTextMarkupData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PreviewRichTextMarkupResponses, unknown, ThrowOnError>({
            url: '/umbraco/block-preview/api/v1/preview/rte',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getSettings<ThrowOnError extends boolean = true>(options?: Options<GetSettingsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetSettingsResponses, unknown, ThrowOnError>({
            url: '/umbraco/block-preview/api/v1/settings',
            ...options
        });
    }
}