// This file is auto-generated by @hey-api/openapi-ts

export type BlockPreviewOptions = {
    blockGrid: BlockTypeSettings;
    blockList: BlockTypeSettings;
    richText: BlockTypeSettings;
};

export type BlockTypeSettings = {
    enabled: boolean;
    viewLocations?: Array<string> | null;
    contentTypes?: Array<string> | null;
    ignoredContentTypes: Array<string>;
    stylesheet?: string | null;
    javaScript?: string | null;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PreviewGridBlockData = {
    body?: string;
    path?: never;
    query?: {
        nodeKey?: string;
        blockEditorAlias?: string;
        contentElementAlias?: string;
        culture?: string;
        documentTypeUnique?: string;
        contentUdi?: string;
        settingsUdi?: string;
        blockIndex?: number;
    };
    url: '/umbraco/block-preview/api/v1/preview/grid';
};

export type PreviewGridBlockResponses = {
    /**
     * OK
     */
    200: string;
};

export type PreviewGridBlockResponse = PreviewGridBlockResponses[keyof PreviewGridBlockResponses];

export type PreviewListBlockData = {
    body?: string;
    path?: never;
    query?: {
        nodeKey?: string;
        blockEditorAlias?: string;
        contentElementAlias?: string;
        culture?: string;
        documentTypeUnique?: string;
        contentUdi?: string;
        settingsUdi?: string;
        blockIndex?: number;
    };
    url: '/umbraco/block-preview/api/v1/preview/list';
};

export type PreviewListBlockResponses = {
    /**
     * OK
     */
    200: string;
};

export type PreviewListBlockResponse = PreviewListBlockResponses[keyof PreviewListBlockResponses];

export type PreviewRichTextMarkupData = {
    body?: string;
    path?: never;
    query?: {
        nodeKey?: string;
        blockEditorAlias?: string;
        contentElementAlias?: string;
        culture?: string;
        documentTypeUnique?: string;
    };
    url: '/umbraco/block-preview/api/v1/preview/rte';
};

export type PreviewRichTextMarkupResponses = {
    /**
     * OK
     */
    200: string;
};

export type PreviewRichTextMarkupResponse = PreviewRichTextMarkupResponses[keyof PreviewRichTextMarkupResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/block-preview/api/v1/settings';
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: BlockPreviewOptions;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:26293' | (string & {});
};