// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:26293' | (string & {});
};

export type BlockPreviewOptions = {
    blockGrid: BlockTypeSettings;
    blockList: BlockTypeSettings;
    richText: BlockTypeSettings;
    singleBlock: BlockTypeSettings;
};

export enum BlockType {
    BLOCK_GRID = 'BlockGrid',
    BLOCK_LIST = 'BlockList',
    RICH_TEXT = 'RichText',
    SINGLE_BLOCK = 'SingleBlock'
}

export type BlockTypeSettings = {
    enabled: boolean;
    viewLocations?: Array<string> | null;
    contentTypes?: Array<string> | null;
    ignoredContentTypes: Array<string>;
    /**
     * @deprecated
     */
    stylesheet?: string | null;
    stylesheets?: Array<string> | null;
};

export type PreviewGridBlockData = {
    body?: string;
    path?: never;
    query?: {
        nodeKey?: string;
        blockEditorAlias?: string;
        contentElementAlias?: string;
        culture?: string;
        documentTypeUnique?: string;
        contentUdi?: string;
        settingsUdi?: string;
        blockIndex?: number;
    };
    url: '/umbraco/block-preview/api/v1/preview/grid';
};

export type PreviewGridBlockResponses = {
    /**
     * OK
     */
    200: string;
};

export type PreviewGridBlockResponse = PreviewGridBlockResponses[keyof PreviewGridBlockResponses];

export type GetGridStylesheetData = {
    body?: never;
    path?: never;
    query?: {
        nodeKey?: string;
        documentTypeUnique?: string;
    };
    url: '/umbraco/block-preview/api/v1/preview/grid/stylesheet';
};

export type GetGridStylesheetResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetGridStylesheetResponse = GetGridStylesheetResponses[keyof GetGridStylesheetResponses];

export type GetGridStylesheetsData = {
    body?: never;
    path?: never;
    query?: {
        nodeKey?: string;
        documentTypeUnique?: string;
    };
    url: '/umbraco/block-preview/api/v1/preview/grid/stylesheets';
};

export type GetGridStylesheetsResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetGridStylesheetsResponse = GetGridStylesheetsResponses[keyof GetGridStylesheetsResponses];

export type PreviewListBlockData = {
    body?: string;
    path?: never;
    query?: {
        nodeKey?: string;
        blockEditorAlias?: string;
        contentElementAlias?: string;
        culture?: string;
        documentTypeUnique?: string;
        contentUdi?: string;
        settingsUdi?: string;
        blockIndex?: number;
    };
    url: '/umbraco/block-preview/api/v1/preview/list';
};

export type PreviewListBlockResponses = {
    /**
     * OK
     */
    200: string;
};

export type PreviewListBlockResponse = PreviewListBlockResponses[keyof PreviewListBlockResponses];

export type GetListStylesheetData = {
    body?: never;
    path?: never;
    query?: {
        nodeKey?: string;
        documentTypeUnique?: string;
    };
    url: '/umbraco/block-preview/api/v1/preview/list/stylesheet';
};

export type GetListStylesheetResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetListStylesheetResponse = GetListStylesheetResponses[keyof GetListStylesheetResponses];

export type GetListStylesheetsData = {
    body?: never;
    path?: never;
    query?: {
        nodeKey?: string;
        documentTypeUnique?: string;
    };
    url: '/umbraco/block-preview/api/v1/preview/list/stylesheets';
};

export type GetListStylesheetsResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetListStylesheetsResponse = GetListStylesheetsResponses[keyof GetListStylesheetsResponses];

export type PreviewRichTextMarkupData = {
    body?: string;
    path?: never;
    query?: {
        nodeKey?: string;
        blockEditorAlias?: string;
        contentElementAlias?: string;
        culture?: string;
        documentTypeUnique?: string;
    };
    url: '/umbraco/block-preview/api/v1/preview/rte';
};

export type PreviewRichTextMarkupResponses = {
    /**
     * OK
     */
    200: string;
};

export type PreviewRichTextMarkupResponse = PreviewRichTextMarkupResponses[keyof PreviewRichTextMarkupResponses];

export type GetRteStylesheetData = {
    body?: never;
    path?: never;
    query?: {
        nodeKey?: string;
        documentTypeUnique?: string;
    };
    url: '/umbraco/block-preview/api/v1/preview/rte/stylesheet';
};

export type GetRteStylesheetResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetRteStylesheetResponse = GetRteStylesheetResponses[keyof GetRteStylesheetResponses];

export type GetRteStylesheetsData = {
    body?: never;
    path?: never;
    query?: {
        nodeKey?: string;
        documentTypeUnique?: string;
    };
    url: '/umbraco/block-preview/api/v1/preview/rte/stylesheets';
};

export type GetRteStylesheetsResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetRteStylesheetsResponse = GetRteStylesheetsResponses[keyof GetRteStylesheetsResponses];

export type PreviewSingleBlockData = {
    body?: string;
    path?: never;
    query?: {
        nodeKey?: string;
        blockEditorAlias?: string;
        contentElementAlias?: string;
        culture?: string;
        documentTypeUnique?: string;
        contentUdi?: string;
        settingsUdi?: string;
        blockIndex?: number;
    };
    url: '/umbraco/block-preview/api/v1/preview/single';
};

export type PreviewSingleBlockResponses = {
    /**
     * OK
     */
    200: string;
};

export type PreviewSingleBlockResponse = PreviewSingleBlockResponses[keyof PreviewSingleBlockResponses];

export type GetSingleBlockStylesheetsData = {
    body?: never;
    path?: never;
    query?: {
        nodeKey?: string;
        documentTypeUnique?: string;
    };
    url: '/umbraco/block-preview/api/v1/preview/single/stylesheets';
};

export type GetSingleBlockStylesheetsResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetSingleBlockStylesheetsResponse = GetSingleBlockStylesheetsResponses[keyof GetSingleBlockStylesheetsResponses];

export type GetStylesheetsData = {
    body?: never;
    path?: never;
    query: {
        blockType: BlockType;
        nodeKey?: string;
        documentTypeUnique?: string;
    };
    url: '/umbraco/block-preview/api/v1/preview/stylesheets';
};

export type GetStylesheetsResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetStylesheetsResponse = GetStylesheetsResponses[keyof GetStylesheetsResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/block-preview/api/v1/settings';
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: BlockPreviewOptions;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];
