//------------------------------------------------------------------------------
// <auto-generated>
//
//    Limbo.Umbraco.ModelsBuilder v13.0.2
//
//    Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Extensions;

#pragma warning disable 0108
#pragma warning disable 0109
#pragma warning disable 1591

namespace Umbraco.Cms.Web.Common.PublishedModels.Elements {

    [PublishedModel("callToActionBlock")]
    public partial class CallToActionBlock : PublishedElementModel {

        #region Helpers

        public new const string ModelTypeAlias = "callToActionBlock";

        public new const PublishedItemType ModelItemType = PublishedItemType.Element;

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
            => PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<CallToActionBlock, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);

        #endregion

        #region Constructors

        public CallToActionBlock(IPublishedElement content, IPublishedValueFallback publishedValueFallback) : base(content, publishedValueFallback) { }

        #endregion

        #region Properties

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("link")]
        public new global::Umbraco.Cms.Core.Models.Link Link
            => this.Value<global::Umbraco.Cms.Core.Models.Link>("link");

        #endregion

    }

    public static class CallToActionBlockExtensions {

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static global::Umbraco.Cms.Core.Models.Link Link(this CallToActionBlock content, string culture = null, string segment = null) {
            return content.Value<global::Umbraco.Cms.Core.Models.Link>("link", culture, segment);
        }

    }

}