//------------------------------------------------------------------------------
// <auto-generated>
//
//    Limbo.Umbraco.ModelsBuilder v13.0.2
//
//    Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Extensions;

#pragma warning disable 0108
#pragma warning disable 0109
#pragma warning disable 1591

namespace Umbraco.Cms.Web.Common.PublishedModels.Elements {

    [PublishedModel("headlineBlock")]
    public partial class HeadlineBlock : PublishedElementModel {

        #region Helpers

        public new const string ModelTypeAlias = "headlineBlock";

        public new const PublishedItemType ModelItemType = PublishedItemType.Element;

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
            => PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<HeadlineBlock, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);

        #endregion

        #region Constructors

        public HeadlineBlock(IPublishedElement content, IPublishedValueFallback publishedValueFallback) : base(content, publishedValueFallback) { }

        #endregion

        #region Properties

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("headline")]
        public new string Headline
            => this.Value<string>("headline");

        #endregion

    }

    public static class HeadlineBlockExtensions {

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static string Headline(this HeadlineBlock content, string culture = null, string segment = null) {
            return content.Value<string>("headline", culture, segment);
        }

    }

}