//------------------------------------------------------------------------------
// <auto-generated>
//
//    Limbo.Umbraco.ModelsBuilder v13.0.2
//
//    Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Extensions;

#pragma warning disable 0108
#pragma warning disable 0109
#pragma warning disable 1591

namespace Umbraco.Cms.Web.Common.PublishedModels.Elements {

    [PublishedModel("heroBlock")]
    public partial class HeroBlock : PublishedElementModel {

        #region Helpers

        public new const string ModelTypeAlias = "heroBlock";

        public new const PublishedItemType ModelItemType = PublishedItemType.Element;

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
            => PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<HeroBlock, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);

        #endregion

        #region Constructors

        public HeroBlock(IPublishedElement content, IPublishedValueFallback publishedValueFallback) : base(content, publishedValueFallback) { }

        #endregion

        #region Properties

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("headline")]
        public new string Headline
            => this.Value<string>("headline");

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("image")]
        public new global::Umbraco.Cms.Core.Models.MediaWithCrops Image
            => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>("image");

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("backgroundColor")]
        public new string BackgroundColor
            => this.Value<string>("backgroundColor");

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("contrast")]
        public new string Contrast
            => this.Value<string>("contrast");

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("contentPicker")]
        public new global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent ContentPicker
            => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>("contentPicker");

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("dropdown")]
        public new string Dropdown
            => this.Value<string>("dropdown");

        #endregion

    }

    public static class HeroBlockExtensions {

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static string Headline(this HeroBlock content, string culture = null, string segment = null) {
            return content.Value<string>("headline", culture, segment);
        }

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static global::Umbraco.Cms.Core.Models.MediaWithCrops Image(this HeroBlock content, string culture = null, string segment = null) {
            return content.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>("image", culture, segment);
        }

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static string BackgroundColor(this HeroBlock content, string culture = null, string segment = null) {
            return content.Value<string>("backgroundColor", culture, segment);
        }

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static string Contrast(this HeroBlock content, string culture = null, string segment = null) {
            return content.Value<string>("contrast", culture, segment);
        }

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent ContentPicker(this HeroBlock content, string culture = null, string segment = null) {
            return content.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>("contentPicker", culture, segment);
        }

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static string Dropdown(this HeroBlock content, string culture = null, string segment = null) {
            return content.Value<string>("dropdown", culture, segment);
        }

    }

}