//------------------------------------------------------------------------------
// <auto-generated>
//
//    Limbo.Umbraco.ModelsBuilder v13.0.2
//
//    Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Extensions;

#pragma warning disable 0108
#pragma warning disable 0109
#pragma warning disable 1591

namespace Umbraco.Cms.Web.Common.PublishedModels.Elements {

    [PublishedModel("sectionSettingsBlock")]
    public partial class SectionSettingsBlock : PublishedElementModel {

        #region Helpers

        public new const string ModelTypeAlias = "sectionSettingsBlock";

        public new const PublishedItemType ModelItemType = PublishedItemType.Element;

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
            => PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<SectionSettingsBlock, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);

        #endregion

        #region Constructors

        public SectionSettingsBlock(IPublishedElement content, IPublishedValueFallback publishedValueFallback) : base(content, publishedValueFallback) { }

        #endregion

        #region Properties

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("backgroundColor")]
        public new string BackgroundColor
            => this.Value<string>("backgroundColor");

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("contrast")]
        public new string Contrast
            => this.Value<string>("contrast");

        #endregion

    }

    public static class SectionSettingsBlockExtensions {

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static string BackgroundColor(this SectionSettingsBlock content, string culture = null, string segment = null) {
            return content.Value<string>("backgroundColor", culture, segment);
        }

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static string Contrast(this SectionSettingsBlock content, string culture = null, string segment = null) {
            return content.Value<string>("contrast", culture, segment);
        }

    }

}