<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <PackageJsonName Condition="$(PackageJsonName) == ''">block-preview</PackageJsonName>
    <PackageJsonPrivate Condition="$(PackageJsonPrivate) == ''">true</PackageJsonPrivate>
    <PackageJsonVersion Condition="$(PackageJsonVersion) == ''">5.2.0</PackageJsonVersion>
    <PackageJsonType Condition="$(PackageJsonType) == ''">module</PackageJsonType>
    <PackageJsonScriptsDev Condition="$(PackageJsonScriptsDev) == ''">vite</PackageJsonScriptsDev>
    <PackageJsonScriptsBuild Condition="$(PackageJsonScriptsBuild) == ''">tsc &amp;&amp; vite build</PackageJsonScriptsBuild>
    <PackageJsonScriptsPreview Condition="$(PackageJsonScriptsPreview) == ''">vite preview</PackageJsonScriptsPreview>
    <PackageJsonScriptsWatch Condition="$(PackageJsonScriptsWatch) == ''">vite build --watch</PackageJsonScriptsWatch>
    <PackageJsonScriptsGenerate Condition="$(PackageJsonScriptsGenerate) == ''">openapi-ts --file openapi-ts.config.ts</PackageJsonScriptsGenerate>
    <PackageJsonDependenciesLit Condition="$(PackageJsonDependenciesLit) == ''">^3.1.0</PackageJsonDependenciesLit>
    <PackageJsonEnginesNode Condition="$(PackageJsonEnginesNode) == ''">&gt;=22.12.0</PackageJsonEnginesNode>
    <PackageJsonDevdependenciesHeyApiClientFetch Condition="$(PackageJsonDevdependenciesHeyApiClientFetch) == ''">^0.13.1</PackageJsonDevdependenciesHeyApiClientFetch>
    <PackageJsonDevdependenciesHeyApiOpenapiTs Condition="$(PackageJsonDevdependenciesHeyApiOpenapiTs) == ''">^0.85.0</PackageJsonDevdependenciesHeyApiOpenapiTs>
    <PackageJsonDevdependenciesUmbracoCmsBackoffice Condition="$(PackageJsonDevdependenciesUmbracoCmsBackoffice) == ''">^17.1.0</PackageJsonDevdependenciesUmbracoCmsBackoffice>
    <PackageJsonDevdependenciesGlob Condition="$(PackageJsonDevdependenciesGlob) == ''">^10.3.10</PackageJsonDevdependenciesGlob>
    <PackageJsonDevdependenciesTypescript Condition="$(PackageJsonDevdependenciesTypescript) == ''">^5.8.3</PackageJsonDevdependenciesTypescript>
    <PackageJsonDevdependenciesVite Condition="$(PackageJsonDevdependenciesVite) == ''">^6.3.5</PackageJsonDevdependenciesVite>
  </PropertyGroup>
</Project>