//------------------------------------------------------------------------------
// <auto-generated>
//
//    Limbo.Umbraco.ModelsBuilder v13.0.2
//
//    Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Extensions;

#pragma warning disable 0108
#pragma warning disable 0109
#pragma warning disable 1591

namespace Umbraco.Cms.Web.Common.PublishedModels.Media {

    [PublishedModel("Image")]
    public partial class Image : PublishedContentModel {

        #region Helpers

        public new const string ModelTypeAlias = "Image";

        public new const PublishedItemType ModelItemType = PublishedItemType.Media;

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
            => PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Image, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);

        #endregion

        #region Constructors

        public Image(IPublishedContent content, IPublishedValueFallback publishedValueFallback) : base(content, publishedValueFallback) { }

        #endregion

        #region Properties

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("umbracoFile")]
        public new global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ImageCropperValue UmbracoFile
            => this.Value<global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ImageCropperValue>("umbracoFile");

        [ImplementPropertyType("umbracoWidth")]
        public new int UmbracoWidth
            => this.Value<int>("umbracoWidth");

        [ImplementPropertyType("umbracoHeight")]
        public new int UmbracoHeight
            => this.Value<int>("umbracoHeight");

        [ImplementPropertyType("umbracoBytes")]
        public new long UmbracoBytes
            => this.Value<long>("umbracoBytes");

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("umbracoExtension")]
        public new string UmbracoExtension
            => this.Value<string>("umbracoExtension");

        #endregion

    }

    public static class ImageExtensions {

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ImageCropperValue UmbracoFile(this Image content, string culture = null, string segment = null) {
            return content.Value<global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ImageCropperValue>("umbracoFile", culture, segment);
        }

        public static int UmbracoWidth(this Image content, string culture = null, string segment = null) {
            return content.Value<int>("umbracoWidth", culture, segment);
        }

        public static int UmbracoHeight(this Image content, string culture = null, string segment = null) {
            return content.Value<int>("umbracoHeight", culture, segment);
        }

        public static long UmbracoBytes(this Image content, string culture = null, string segment = null) {
            return content.Value<long>("umbracoBytes", culture, segment);
        }

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static string UmbracoExtension(this Image content, string culture = null, string segment = null) {
            return content.Value<string>("umbracoExtension", culture, segment);
        }

    }

}