//------------------------------------------------------------------------------
// <auto-generated>
//
//    Limbo.Umbraco.ModelsBuilder v13.0.2
//
//    Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Extensions;

#pragma warning disable 0108
#pragma warning disable 0109
#pragma warning disable 1591

namespace Umbraco.Cms.Web.Common.PublishedModels.Media {

    [PublishedModel("umbracoMediaAudio")]
    public partial class UmbracoMediaAudio : PublishedContentModel {

        #region Helpers

        public new const string ModelTypeAlias = "umbracoMediaAudio";

        public new const PublishedItemType ModelItemType = PublishedItemType.Media;

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
            => PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<UmbracoMediaAudio, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);

        #endregion

        #region Constructors

        public UmbracoMediaAudio(IPublishedContent content, IPublishedValueFallback publishedValueFallback) : base(content, publishedValueFallback) { }

        #endregion

        #region Properties

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("umbracoFile")]
        public new string UmbracoFile
            => this.Value<string>("umbracoFile");

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("umbracoExtension")]
        public new string UmbracoExtension
            => this.Value<string>("umbracoExtension");

        [ImplementPropertyType("umbracoBytes")]
        public new long UmbracoBytes
            => this.Value<long>("umbracoBytes");

        #endregion

    }

    public static class UmbracoMediaAudioExtensions {

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static string UmbracoFile(this UmbracoMediaAudio content, string culture = null, string segment = null) {
            return content.Value<string>("umbracoFile", culture, segment);
        }

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static string UmbracoExtension(this UmbracoMediaAudio content, string culture = null, string segment = null) {
            return content.Value<string>("umbracoExtension", culture, segment);
        }

        public static long UmbracoBytes(this UmbracoMediaAudio content, string culture = null, string segment = null) {
            return content.Value<long>("umbracoBytes", culture, segment);
        }

    }

}