//------------------------------------------------------------------------------
// <auto-generated>
//
//    Limbo.Umbraco.ModelsBuilder v13.0.2
//
//    Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Extensions;

#pragma warning disable 0108
#pragma warning disable 0109
#pragma warning disable 1591

namespace Umbraco.Cms.Web.Common.PublishedModels.Members {

    [PublishedModel("Member")]
    public partial class Member : PublishedContentModel {

        #region Helpers

        public new const string ModelTypeAlias = "Member";

        public new const PublishedItemType ModelItemType = PublishedItemType.Member;

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
            => PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Member, TValue>> selector)
            => PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);

        #endregion

        #region Constructors

        public Member(IPublishedContent content, IPublishedValueFallback publishedValueFallback) : base(content, publishedValueFallback) { }

        #endregion

        #region Properties

        [global::System.Diagnostics.CodeAnalysis.MaybeNull]
        [ImplementPropertyType("umbracoMemberComments")]
        public new string UmbracoMemberComments
            => this.Value<string>("umbracoMemberComments");

        #endregion

    }

    public static class MemberExtensions {

        [return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
        public static string UmbracoMemberComments(this Member content, string culture = null, string segment = null) {
            return content.Value<string>("umbracoMemberComments", culture, segment);
        }

    }

}